### ISSUE TITLE
Fix crashing after entering coordinate 

### ISSUE THREAD

**Issue by k1s** [b0noI/XO-hexlet#25]
In

 try (final Scanner in = new Scanner(System.in)) 

in 

ConsoleCoordinateReader implements ICoordinateReader {
    @Override
    public int askCoordinate(String coordinateName)

it's possible anyhow get the next problem:

Please enter move point for: X
Please input X:2
Exception in thread "main" Please input Y:java.util.NoSuchElementException
    at java.util.Scanner.throwFor(Scanner.java:862)
    at java.util.Scanner.next(Scanner.java:1485)
    at java.util.Scanner.nextInt(Scanner.java:2117)
    at java.util.Scanner.nextInt(Scanner.java:2076)
    at io.hexlet.xo.view.reader.ConsoleCoordinateReader.askCoordinate(ConsoleCoordinateReader.java:12)
    at io.hexlet.xo.view.ConsoleView.askPoint(ConsoleView.java:63)
    at io.hexlet.xo.view.ConsoleView.move(ConsoleView.java:53)
    at io.hexlet.xo.XOCLI.main(XOCLI.java:31)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

Cannot manage why this is possible anyway, may be OS/IDE local bug.

**Comment by k1s** [comment]
Though it's definitely bug in try with scanner – can repeat it on another project.

**Comment by andrewzhurov** [comment]
Maybe that's feature of the Linux's console ?
I got it too. But b0noi don't

**Comment by k1s** [comment]
I got the error on both Mac & Windows for the same .jar, unfortunately I
hadn't any time to investigate this.

**Comment by k1s** [comment]
In this code Scanner is implicitly closed by try-catch, so it closes System.in at all, but it's really not need, to close System.in. Also http://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/input/CloseShieldInputStream.html might be used for that purpose, but I can't see any necessity for this.

**Comment by k1s** [comment]
Done in https://github.com/b0noI/XO-hexlet/pull/29
